#!/bin/sh

make -C ../libft/ fclean && make -C ../libft/
make -C ../ fclean && make -C ../
gcc -Wall -Wextra -Werror -I../ -L../ -L../libft -lft -lftprintf main.c
make -C ../libft/ fclean && make -C ../ fclean

